<a href="https://colab.research.google.com/github/ashwanimsajeev/ashwanims/blob/main/Car_Price_Prediction_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing necessary packages and libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

Data Loading

In [4]:
df=pd.read_csv("car_price.csv")
df

,Unnamed: 0,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,0,Jeep Compass 2.0 Longitude Option BSIV,10.03 Lakh,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,1,Renault Duster RXZ Turbo CVT,12.83 Lakh,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,2,Toyota Camry 2.5 G,16.40 Lakh,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,3,Honda Jazz VX CVT,7.77 Lakh,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,4,Volkswagen Polo 1.2 MPI Highline,5.15 Lakh,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats
...,...,...,...,...,...,...,...,...,...,...
5507,5507,BMW X1 sDrive 20d xLine,28.90 Lakh,"45,000 kms",Diesel,Automatic,1st Owner,2018,2995 cc,7 Seats
5508,5508,BMW M Series M4 Coupe,64.90 Lakh,"29,000 kms",Petrol,Automatic,2nd Owner,2015,1968 cc,5 Seats
5509,5509,Jaguar XF 2.2 Litre Luxury,13.75 Lakh,"90,000 kms",Diesel,Automatic,2nd Owner,2013,2755 cc,5 Seats
5510,5510,BMW 7 Series 730Ld,29.90 Lakh,"79,000 kms",Diesel,Automatic,3rd Owner,2015,2967 cc,6 Seats
5511,5511,BMW 5 Series 520d M Sport,31.90 Lakh,"42,000 kms",Diesel,Automatic,2nd Owner,2017,1991 cc,5 Seats

Summary of the DataFrame

In [ ]:
df.info()

Display first 10 rows of the DataFrame

In [5]:
df.head(10)

,Unnamed: 0,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,0,Jeep Compass 2.0 Longitude Option BSIV,10.03 Lakh,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,1,Renault Duster RXZ Turbo CVT,12.83 Lakh,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,2,Toyota Camry 2.5 G,16.40 Lakh,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,3,Honda Jazz VX CVT,7.77 Lakh,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,4,Volkswagen Polo 1.2 MPI Highline,5.15 Lakh,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats
5,5,Volkswagen Vento 1.2 TSI Highline AT,7.66 Lakh,"49,719 kms",Petrol,Automatic,1st Owner,2017,1197 cc,5 Seats
6,6,Volkswagen Vento 1.2 TSI Highline Plus AT,7.58 Lakh,"43,688 kms",Petrol,Automatic,1st Owner,2017,1197 cc,5 Seats
7,7,Honda WR-V VX Diesel,11.60 Lakh,"14,470 kms",Diesel,Manual,1st Owner,2021,1498 cc,5 Seats
8,8,Honda City i VTEC CVT SV,6.99 Lakh,"21,429 kms",Petrol,Automatic,1st Owner,2015,1497 cc,5 Seats
9,9,Renault Duster Petrol RXS CVT,7.53 Lakh,"31,750 kms",Petrol,Automatic,1st Owner,2017,1498 cc,5 Seats

Selecting the necessary columns

In [6]:
columns = ['car_prices_in_rupee','kms_driven','fuel_type','transmission','ownership','manufacture','engine','Seats']
df = df[columns]
df

,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,10.03 Lakh,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,12.83 Lakh,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,16.40 Lakh,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,7.77 Lakh,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,5.15 Lakh,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats
...,...,...,...,...,...,...,...,...
5507,28.90 Lakh,"45,000 kms",Diesel,Automatic,1st Owner,2018,2995 cc,7 Seats
5508,64.90 Lakh,"29,000 kms",Petrol,Automatic,2nd Owner,2015,1968 cc,5 Seats
5509,13.75 Lakh,"90,000 kms",Diesel,Automatic,2nd Owner,2013,2755 cc,5 Seats
5510,29.90 Lakh,"79,000 kms",Diesel,Automatic,3rd Owner,2015,2967 cc,6 Seats
5511,31.90 Lakh,"42,000 kms",Diesel,Automatic,2nd Owner,2017,1991 cc,5 Seats

Filtering the data of the 'kms_driven' column into numeric values

In [16]:
df['kms_driven']

0       86226
1       13248
2       60343
3       26696
4       69414
        ...
5507    45000
5508    29000
5509    90000
5510    79000
5511    42000
Name: kms_driven, Length: 5512, dtype: int64

Datatype checking

In [15]:
print(df['kms_driven'].dtype)

int64

List all the unique values of the 'fuel_type' column

In [17]:
df['fuel_type'].unique()

array(['Diesel', 'Petrol', 'Cng', 'Electric', 'Lpg'], dtype=object)

Convert categorical data into numerical labels

In [18]:
label_encoder = LabelEncoder()
df['fuel_type']= label_encoder.fit_transform(df['fuel_type'])
df['fuel_type']

<ipython-input-18-a22177ce370f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['fuel_type']= label_encoder.fit_transform(df['fuel_type'])

0       1
1       4
2       4
3       4
4       4
       ..
5507    1
5508    4
5509    1
5510    1
5511    1
Name: fuel_type, Length: 5512, dtype: int64

Finding the unique values of the 'transmission' column

In [19]:
df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

Convert categorical data into numerical labels

In [20]:
df['transmission']= label_encoder.fit_transform(df['transmission'])
df['transmission']

<ipython-input-20-853fa4abf90d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['transmission']= label_encoder.fit_transform(df['transmission'])

0       1
1       0
2       0
3       0
4       1
       ..
5507    0
5508    0
5509    0
5510    0
5511    0
Name: transmission, Length: 5512, dtype: int64

In [21]:
df

,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,10.03 Lakh,86226,1,1,1st Owner,2017,1956 cc,5 Seats
1,12.83 Lakh,13248,4,0,1st Owner,2021,1330 cc,5 Seats
2,16.40 Lakh,60343,4,0,1st Owner,2016,2494 cc,5 Seats
3,7.77 Lakh,26696,4,0,1st Owner,2018,1199 cc,5 Seats
4,5.15 Lakh,69414,4,1,1st Owner,2016,1199 cc,5 Seats
...,...,...,...,...,...,...,...,...
5507,28.90 Lakh,45000,1,0,1st Owner,2018,2995 cc,7 Seats
5508,64.90 Lakh,29000,4,0,2nd Owner,2015,1968 cc,5 Seats
5509,13.75 Lakh,90000,1,0,2nd Owner,2013,2755 cc,5 Seats
5510,29.90 Lakh,79000,1,0,3rd Owner,2015,2967 cc,6 Seats
5511,31.90 Lakh,42000,1,0,2nd Owner,2017,1991 cc,5 Seats

Unique values of 'ownership'

In [22]:
df['ownership'].unique()

array(['1st Owner', '2nd Owner', '3rd Owner', '4th Owner', '5th Owner',
       '0th Owner'], dtype=object)

Convert categorical data into numerical labels

In [24]:
df['ownership']=label_encoder.fit_transform(df['ownership'])
df['ownership']

<ipython-input-24-2bfdc088c91b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ownership']=label_encoder.fit_transform(df['ownership'])

0       1
1       1
2       1
3       1
4       1
       ..
5507    1
5508    2
5509    2
5510    3
5511    2
Name: ownership, Length: 5512, dtype: int64

In [25]:
df

,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,10.03 Lakh,86226,1,1,1,2017,1956 cc,5 Seats
1,12.83 Lakh,13248,4,0,1,2021,1330 cc,5 Seats
2,16.40 Lakh,60343,4,0,1,2016,2494 cc,5 Seats
3,7.77 Lakh,26696,4,0,1,2018,1199 cc,5 Seats
4,5.15 Lakh,69414,4,1,1,2016,1199 cc,5 Seats
...,...,...,...,...,...,...,...,...
5507,28.90 Lakh,45000,1,0,1,2018,2995 cc,7 Seats
5508,64.90 Lakh,29000,4,0,2,2015,1968 cc,5 Seats
5509,13.75 Lakh,90000,1,0,2,2013,2755 cc,5 Seats
5510,29.90 Lakh,79000,1,0,3,2015,2967 cc,6 Seats
5511,31.90 Lakh,42000,1,0,2,2017,1991 cc,5 Seats

Convert categorical data into numerical labels

In [26]:
df['engine']=label_encoder.fit_transform(df['engine'])
df['engine']

<ipython-input-26-71993525350c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['engine']=label_encoder.fit_transform(df['engine'])

0        60
1        19
2        88
3        14
4        14
       ...
5507    110
5508     61
5509     98
5510    104
5511     65
Name: engine, Length: 5512, dtype: int64

Unique values of the column "seats"

In [27]:
df.Seats.unique()

array(['5 Seats', '6 Seats', '7 Seats', '4 Seats', '8 Seats', '2 Seats'],
      dtype=object)

Convert categorical data into numerical labels

In [28]:
df['Seats']=label_encoder.fit_transform(df['Seats'])
df['Seats']

<ipython-input-28-1bba7b137d7c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Seats']=label_encoder.fit_transform(df['Seats'])

0       2
1       2
2       2
3       2
4       2
       ..
5507    4
5508    2
5509    2
5510    3
5511    2
Name: Seats, Length: 5512, dtype: int64

In [30]:
df

,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,10.03 Lakh,86226,1,1,1,2017,60,2
1,12.83 Lakh,13248,4,0,1,2021,19,2
2,16.40 Lakh,60343,4,0,1,2016,88,2
3,7.77 Lakh,26696,4,0,1,2018,14,2
4,5.15 Lakh,69414,4,1,1,2016,14,2
...,...,...,...,...,...,...,...,...
5507,28.90 Lakh,45000,1,0,1,2018,110,4
5508,64.90 Lakh,29000,4,0,2,2015,61,2
5509,13.75 Lakh,90000,1,0,2,2013,98,2
5510,29.90 Lakh,79000,1,0,3,2015,104,3
5511,31.90 Lakh,42000,1,0,2,2017,65,2

In [31]:
df['car_prices_in_rupee'] = df['car_prices_in_rupee'].str.split().str[0].str.replace(',','').astype(float)
df['car_prices_in_rupee']

<ipython-input-31-d0fd85d2d3b9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['car_prices_in_rupee'] = df['car_prices_in_rupee'].str.split().str[0].str.replace(',','').astype(float)

0       10.03
1       12.83
2       16.40
3        7.77
4        5.15
        ...
5507    28.90
5508    64.90
5509    13.75
5510    29.90
5511    31.90
Name: car_prices_in_rupee, Length: 5512, dtype: float64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5512 entries, 0 to 5511
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_prices_in_rupee  5512 non-null   float64
 1   kms_driven           5512 non-null   int64
 2   fuel_type            5512 non-null   int64
 3   transmission         5512 non-null   int64
 4   ownership            5512 non-null   int64
 5   manufacture          5512 non-null   int64
 6   engine               5512 non-null   int64
 7   Seats                5512 non-null   int64
dtypes: float64(1), int64(7)
memory usage: 344.6 KB

X labels

In [37]:
x = df[['kms_driven','fuel_type','transmission','ownership','manufacture','engine','Seats']]
x

,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,86226,1,1,1,2017,60,2
1,13248,4,0,1,2021,19,2
2,60343,4,0,1,2016,88,2
3,26696,4,0,1,2018,14,2
4,69414,4,1,1,2016,14,2
...,...,...,...,...,...,...,...
5507,45000,1,0,1,2018,110,4
5508,29000,4,0,2,2015,61,2
5509,90000,1,0,2,2013,98,2
5510,79000,1,0,3,2015,104,3
5511,42000,1,0,2,2017,65,2

Y labels

In [34]:
y = df[['car_prices_in_rupee']]
y

      car_prices_in_rupee
0                   10.03
1                   12.83
2                   16.40
3                    7.77
4                    5.15
...                   ...
5507                28.90
5508                64.90
5509                13.75
5510                29.90
5511                31.90

[5512 rows x 1 columns]

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [36]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [38]:
prediction = lr.predict(x_test)
prediction

array([[-2463.31243147],
       [  199.57276627],
       [ 5476.85876143],
       ...,
       [  500.95248798],
       [ 1710.86575291],
       [-3478.61663816]])

In [39]:
print('Mean Absolute Error',mean_absolute_error(y_test,prediction))
print('Mean Squared Error',mean_squared_error(y_test,prediction))
print('R2 Score',r2_score(y_test,prediction))

Mean Absolute Error 4270.716654113465
Mean Squared Error 104405091.48652703
R2 Score 0.09334523916313375